# Generated by Django 3.0.6 on 2022-07-26 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Soluciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libros',
            name='autor',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='libros',
            name='edicion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='libros',
            name='perfilId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Soluciones.perfil', verbose_name='Perfil'),
        ),
        migrations.AlterField(
            model_name='libros',
            name='titulo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
