# Generated by Django 3.0.6 on 2022-07-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Soluciones', '0002_auto_20220726_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='tematicas',
            name='agregadoPor',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='libros',
            name='autor',
            field=models.CharField(max_length=50, null=True, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='libros',
            name='edicion',
            field=models.CharField(max_length=50, null=True, verbose_name='Edición'),
        ),
        migrations.AlterField(
            model_name='libros',
            name='titulo',
            field=models.CharField(max_length=50, null=True, verbose_name='Título'),
        ),
    ]
