# Generated by Django 3.0.6 on 2022-07-31 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Soluciones', '0003_auto_20220726_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='correoValidacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=254)),
                ('codigo', models.IntegerField()),
                ('validado', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='tematicas',
            name='agregadoPor',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tematicas',
            name='perfilId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Soluciones.perfil', verbose_name='Perfil'),
        ),
        migrations.AlterField(
            model_name='tematicas',
            name='temaNombre',
            field=models.CharField(max_length=50, null=True, verbose_name='Nombre del Tema'),
        ),
    ]
